# Generated by Django 3.0.8 on 2020-07-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_orm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='books',
            new_name='bookss',
        ),
    ]
