# Generated by Django 3.0.8 on 2020-07-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_orm_app', '0002_auto_20200712_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='bookss',
            new_name='books',
        ),
    ]
